server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aidsys_material
    username: aidsys_user
    password: 123456
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: material_sch

## Actuator ##
management:
  endpoints:
    web:
      exposure:
        include: health,info

## OpenApi Settings ##
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/docs/swagger-ui.html"

openapi:
  app:
    title: "Aidsys Material API"
    description: "This project aims to provide material operations for Aidsys project."
    version: 1.0
    contact : "Contact Support"
    email: "tuncay@talls.tech"
    licence: "Tallstech 1.0"
    url: "https://talls.tech"
